name: CICD

on:
  workflow_dispatch:
    inputs:
      environments:
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
  code:
    runs-on: ubuntu-latest
    steps: 
      - name: code building
        run: echo "Code ran"

  build:
    runs-on: ubuntu-latest
    steps: 
      - name: building code
        run: echo "Code build"

  test:
    runs-on: ubuntu-latest
    steps: 
      - name: testing code
        run: echo "Code tested successfully"

  deploy:
    if: ${{ inputs.environments == 'dev' }}
    runs-on: ubuntu-latest
    steps: 
      - name: deploying code
        run: echo "Code deployed"
